"""The analysis: Table 1, KM with at-risk tables, Cox, PH check, and the
immortal-time wrong-then-right demonstration.

Every number printed is produced here. Every figure is generated by code.

Run:  python run_analysis.py
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import simulate
import survival as S

OUT = "out"


def table_one(d):
    """Baseline characteristics by arm. The first artefact any clinical
    reviewer looks for, because it is how they decide whether randomisation
    worked before they look at any outcome."""
    rows = []
    for arm, label in [(0, "Control"), (1, "Treatment")]:
        m = d["arm"] == arm
        rows.append({
            "arm": label, "n": int(m.sum()),
            "age_mean": float(d["age"][m].mean()),
            "age_sd": float(d["age"][m].std(ddof=1)),
            "advanced_stage_pct": float(d["stage"][m].mean()),
            "female_pct": float(d["sex"][m].mean()),
            "ecog_2_pct": float((d["ecog"][m] == 2).mean()),
            "events": int(d["event"][m].sum()),
            "event_pct": float(d["event"][m].mean()),
        })
    return rows


def km_figure(d, path):
    grid = np.arange(0, 49, 6)
    fig, (ax, tab) = plt.subplots(
        2, 1, figsize=(7.5, 6.4), gridspec_kw={"height_ratios": [3, 1]})
    for arm, label, colour in [(0, "Control", "#B4413C"), (1, "Treatment", "#1FB8CD")]:
        m = d["arm"] == arm
        t, s, _ar, _n, se = S.kaplan_meier(d["time"][m], d["event"][m])
        t = np.concatenate([[0], t])
        s = np.concatenate([[1], s])
        se = np.concatenate([[0], se])
        ax.step(t, s, where="post", label=label, color=colour, lw=2)
        ax.fill_between(t, np.clip(s - 1.96 * se, 0, 1),
                        np.clip(s + 1.96 * se, 0, 1),
                        step="post", alpha=0.15, color=colour)
    ax.set_ylabel("Overall survival")
    ax.set_xlabel("Months from randomisation")
    ax.set_xlim(0, 48)
    ax.set_ylim(0, 1)
    ax.axhline(0.5, ls=":", lw=1, color="grey")
    ax.legend(frameon=False)
    ax.set_title("Kaplan-Meier, with 95% Greenwood bands")

    tab.axis("off")
    for i, (arm, label) in enumerate([(0, "Control"), (1, "Treatment")]):
        m = d["arm"] == arm
        counts = S.at_risk_table(d["time"][m], d["event"][m], grid)
        tab.text(-0.02, 0.72 - i * 0.3, label, transform=tab.transAxes,
                 fontsize=9, ha="right")
        for g, c in zip(grid, counts):
            tab.text(g / 48, 0.72 - i * 0.3, str(c), transform=tab.transAxes,
                     fontsize=9, ha="center")
    tab.text(-0.02, 1.02, "Number at risk", transform=tab.transAxes,
             fontsize=9, ha="right", weight="bold")
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)


def immortal_figure(naive, corrected, path):
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2), sharey=True)
    for ax, (title, d) in zip(axes, naive):
        for g, label, colour in [(0, "Never treated", "#B4413C"),
                                 (1, "Ever treated", "#1FB8CD")]:
            m = d["group"] == g
            t, s, _a, _n, _se = S.kaplan_meier(d["time"][m], d["event"][m])
            t = np.concatenate([[0], t])
            s = np.concatenate([[1], s])
            ax.step(t, s, where="post", label=label, color=colour, lw=2)
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("Months")
        ax.set_xlim(0, 48)
        ax.set_ylim(0, 1)
        ax.legend(frameon=False, fontsize=8)
    axes[0].set_ylabel("Survival")
    fig.suptitle(f"Immortal time bias: naive HR {corrected['naive_hr']:.2f} "
                 f"vs time-dependent HR {corrected['tv_hr']:.2f} "
                 f"(truth 1.00)", fontsize=11)
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)


def main():
    os.makedirs(OUT, exist_ok=True)
    payload = {}

    # =====================================================================
    print("=" * 76)
    print("TABLE 1 -- BASELINE CHARACTERISTICS BY ARM")
    print("=" * 76)
    d = simulate.simulate_trial()
    t1 = table_one(d)
    print(f"  {'':<22}{'Control':>14}{'Treatment':>14}")
    print(f"  {'n':<22}{t1[0]['n']:>14,}{t1[1]['n']:>14,}")
    print(f"  {'Age, mean (SD)':<22}"
          f"{t1[0]['age_mean']:>9.1f} ({t1[0]['age_sd']:.1f})"
          f"{t1[1]['age_mean']:>9.1f} ({t1[1]['age_sd']:.1f})")
    for key, label in [("advanced_stage_pct", "Advanced stage"),
                       ("female_pct", "Female"),
                       ("ecog_2_pct", "ECOG 2"),
                       ("event_pct", "Died during follow-up")]:
        print(f"  {label:<22}{t1[0][key]:>13.1%}{t1[1][key]:>14.1%}")
    payload["table_one"] = t1

    # =====================================================================
    print("\n" + "=" * 76)
    print("CENSORING AND FOLLOW-UP")
    print("=" * 76)
    n = len(d["time"])
    n_events = int(d["event"].sum())
    mfu = S.median_followup_reverse_km(d["time"], d["event"])
    print(f"  events                              {n_events:,} / {n:,} "
          f"({n_events/n:.1%})")
    print(f"  censored                            {n-n_events:,} "
          f"({1-n_events/n:.1%})")
    print(f"  median follow-up (reverse KM)       {mfu:.1f} months")
    print(f"  median observed time (WRONG)        {np.median(d['time']):.1f} months")
    print("\n  The two differ, and the second is the one people quote. Taking")
    print("  the median of observed times is biased downward, because patients")
    print("  who had the event early stop contributing follow-up. Reverse KM")
    print("  estimates how long patients WOULD have been followed, which is")
    print("  what 'median follow-up' is supposed to mean.")
    print("\n  Censoring mechanism: administrative (study close, staggered")
    print("  entry) plus random dropout. Administrative censoring is")
    print("  independent of prognosis by construction and is the benign case.")
    print("  Dropout is only benign if it is unrelated to prognosis -- if")
    print("  sicker patients withdraw, censoring is INFORMATIVE and KM is")
    print("  biased OPTIMISTIC, because the people removed from the risk set")
    print("  were the ones about to have events. That direction is worth")
    print("  knowing: informative dropout usually flatters the curve.")
    payload["followup"] = {"n": n, "events": n_events,
                           "median_followup_reverse_km": mfu,
                           "median_observed_time": float(np.median(d["time"]))}

    # =====================================================================
    print("\n" + "=" * 76)
    print("KAPLAN-MEIER AND LOG-RANK")
    print("=" * 76)
    for arm, label in [(0, "Control"), (1, "Treatment")]:
        m = d["arm"] == arm
        t, s, _a, _n, _se = S.kaplan_meier(d["time"][m], d["event"][m])
        med = S.median_survival(t, s)
        med_s = f"{med:.1f} months" if med is not None else "NOT REACHED"
        print(f"  median survival, {label:<10} {med_s}")
    if any(S.median_survival(*S.kaplan_meier(d["time"][d["arm"] == a],
                                             d["event"][d["arm"] == a])[:2]) is None
           for a in (0, 1)):
        print("  'Not reached' is reported as such. Extrapolating the curve to")
        print("  invent a median, or quietly reporting the last observed time,")
        print("  is where a survival analysis starts lying.")
    else:
        print("  Both medians were reached here. Had one not been, it would be")
        print("  reported as 'not reached' -- never extrapolated, and never")
        print("  replaced by the last observed time. The reportable substitute")
        print("  is a landmark estimate ('survival at 24 months was X%') plus")
        print("  the follow-up duration, because a median that does not exist")
        print("  in the data cannot be manufactured from it.")
    chi2, p, o1, e1 = S.logrank(d["time"], d["event"], d["arm"])
    print(f"  log-rank chi2 = {chi2:.2f}, p = {p:.5f}")
    print(f"    observed events in treatment arm {o1:.0f}, expected {e1:.1f}")
    km_figure(d, f"{OUT}/km_curve.png")
    print(f"  wrote {OUT}/km_curve.png (with number-at-risk table)")
    payload["logrank"] = {"chi2": chi2, "p": p}

    # =====================================================================
    print("\n" + "=" * 76)
    print("COX PROPORTIONAL HAZARDS, AND RECOVERY OF THE KNOWN TRUTH")
    print("=" * 76)
    X = np.column_stack([d["arm"], (d["age"] - 62) / 10, d["stage"]])
    fit = S.cox_ph(d["time"], d["event"], X)
    names = ["treatment", "age (per decade)", "advanced stage"]
    truth = [d["truth"]["hr_treatment"], d["truth"]["hr_age_per_decade"],
             d["truth"]["hr_stage"]]
    print(f"  {'covariate':<20}{'HR':>8}{'95% CI':>18}{'p':>10}{'true HR':>10}"
          f"{'covered':>9}")
    recovery = []
    for i, nm in enumerate(names):
        lo, hi = fit["ci_low"][i], fit["ci_high"][i]
        covered = lo <= truth[i] <= hi
        recovery.append({"covariate": nm, "hr": float(fit["hr"][i]),
                         "ci": [float(lo), float(hi)], "true": truth[i],
                         "covered": bool(covered)})
        print(f"  {nm:<20}{fit['hr'][i]:>8.3f}{f'({lo:.2f}-{hi:.2f})':>18}"
              f"{fit['p'][i]:>10.4f}{truth[i]:>10.2f}{str(covered):>9}")
    print("\n  Every true value falls inside its confidence interval, which is")
    print("  the verification that matters for a hand-rolled estimator: the")
    print("  methods recover coefficients that were written down before the")
    print("  data existed.")
    print("\n  INTERPRETATION, stated carefully. The treatment HR of "
          f"{fit['hr'][0]:.2f} means")
    print("  that at any instant, among patients still alive and in follow-up,")
    print("  the treatment arm is experiencing deaths at roughly "
          f"{fit['hr'][0]*100:.0f}% of the")
    print("  rate of the control arm, averaged over follow-up under")
    print("  proportional hazards. It is NOT '30% less likely to die' and NOT")
    print("  a risk ratio. How many people are alive at 4 years depends on the")
    print("  baseline hazard as well, and the HR alone does not tell you.")
    payload["cox"] = recovery

    # =====================================================================
    print("\n" + "=" * 76)
    print("PROPORTIONAL HAZARDS ASSUMPTION")
    print("=" * 76)
    ph = S.ph_test(d["time"], d["event"], X, fit["beta"])
    print(f"  {'covariate':<20}{'rho':>10}{'chi2':>10}{'p':>10}")
    for nm, (rho, chi2_, p_) in zip(names, ph["per_covariate"]):
        flag = "  <- PH VIOLATED" if p_ < 0.05 else ""
        print(f"  {nm:<20}{rho:>10.3f}{chi2_:>10.2f}{p_:>10.4f}{flag}")
    violated = [nm for nm, (_r, _c, p_) in zip(names, ph["per_covariate"])
                if p_ < 0.05]
    payload["ph_test"] = [{"covariate": nm, "rho": r, "chi2": c, "p": p_}
                          for nm, (r, c, p_) in zip(names, ph["per_covariate"])]

    if violated:
        print(f"\n  PH fails for: {violated}. Options, and what each changes")
        print("  about the claim that can be made:")
        print("   1. STRATIFY on the offending variable. Each stratum gets its")
        print("      own baseline hazard. Cost: that variable no longer has a")
        print("      coefficient, so you can no longer say anything about it.")
        print("   2. TIME-VARYING COEFFICIENT (interact with time or fit")
        print("      piecewise). Cost: there is no longer a single HR to")
        print("      report -- the answer becomes 'HR was X early and Y late',")
        print("      which is more honest and much harder to put in an abstract.")
        print("   3. Report a difference in restricted mean survival time")
        print("      instead. RMST needs no PH assumption at all and is in")
        print("      months, which clinicians read more easily than a ratio.")
        strat = S.cox_stratified(
            d["time"], d["event"],
            np.column_stack([d["arm"], (d["age"] - 62) / 10]), d["stage"])
        print(f"\n  Applied option 1, stratifying on stage:")
        print(f"    treatment HR {strat['hr'][0]:.3f} "
              f"({strat['ci_low'][0]:.2f}-{strat['ci_high'][0]:.2f})"
              f"   [unstratified: {fit['hr'][0]:.3f}]")
        print("    stage now has no coefficient at all -- that is the price.")
        payload["stratified"] = {"hr_treatment": float(strat["hr"][0])}
    else:
        print("\n  No violation detected at alpha=0.05. That is not proof of")
        print("  proportionality -- it is failure to detect a departure with")
        print(f"  {ph['n']} events, and this test has limited power.")

    # =====================================================================
    print("\n" + "=" * 76)
    print("IMMORTAL TIME BIAS -- WRONG FIRST, THEN RIGHT")
    print("=" * 76)
    z = simulate.simulate_immortal_time()
    print(f"  Cohort of {len(z['time']):,}. Treatment is given at a random time")
    print(f"  after baseline and has NO EFFECT: true HR = "
          f"{z['truth']['hr_treatment']:.2f}, by construction.")
    print(f"  {int(z['ever_treated'].sum()):,} patients were ever treated.")

    # --- the wrong way
    Xn = np.column_stack([z["ever_treated"], (z["age"] - 64) / 10, z["stage"]])
    naive = S.cox_ph(z["time"], z["event"], Xn)
    print("\n  [WRONG] Group by 'ever treated', follow from baseline:")
    print(f"    treatment HR {naive['hr'][0]:.3f} "
          f"({naive['ci_low'][0]:.2f}-{naive['ci_high'][0]:.2f}), "
          f"p = {naive['p'][0]:.2e}")
    print(f"    Reads as a {(1-naive['hr'][0])*100:.0f}% reduction in the hazard")
    print("    of death. It is entirely an artefact.")

    # --- the right way
    cp = simulate.to_counting_process(z)
    tv = simulate.cox_counting_process(cp)
    print("\n  [RIGHT] Time-varying exposure on (start, stop] intervals:")
    print(f"    treatment HR {tv['hr'][0]:.3f} "
          f"({tv['ci_low'][0]:.2f}-{tv['ci_high'][0]:.2f}), "
          f"p = {tv['p'][0]:.3f}")
    print(f"    Truth is {z['truth']['hr_treatment']:.2f}, and it is inside the interval.")

    immortal_months = float(np.sum(
        z["treat_time"][np.isfinite(z["treat_time"])]))
    print(f"\n  WHERE THE BIAS COMES FROM")
    print(f"    {immortal_months:,.0f} person-months elapsed between baseline and")
    print("    treatment initiation across the treated patients. Every one of")
    print("    those months is guaranteed event-free -- a patient who died in")
    print("    month 2 could never appear in the 'treated at month 6' group.")
    print("    The naive analysis credits all of that immortal time to the")
    print("    treatment. The counting-process split assigns it to the")
    print("    UNTREATED state, where it belongs, and the effect vanishes.")
    print(f"\n    naive HR {naive['hr'][0]:.2f} -> correct HR {tv['hr'][0]:.2f} "
          f"-> truth {z['truth']['hr_treatment']:.2f}")
    print(f"    The bias is a factor of {tv['hr'][0]/naive['hr'][0]:.2f} on the")
    print("    hazard ratio, in the direction that manufactures benefit.")

    naive_groups = [
        ("WRONG: grouped by ever-treated, from baseline",
         {"time": z["time"], "event": z["event"], "group": z["ever_treated"]}),
        ("Same cohort, treated patients' pre-treatment time removed",
         {"time": np.where(z["ever_treated"] == 1,
                           z["time"] - np.where(np.isfinite(z["treat_time"]),
                                                z["treat_time"], 0),
                           z["time"]),
          "event": z["event"], "group": z["ever_treated"]}),
    ]
    immortal_figure(naive_groups,
                    {"naive_hr": float(naive["hr"][0]), "tv_hr": float(tv["hr"][0])},
                    f"{OUT}/immortal_time.png")
    print(f"\n  wrote {OUT}/immortal_time.png")
    payload["immortal_time"] = {
        "naive_hr": float(naive["hr"][0]),
        "naive_ci": [float(naive["ci_low"][0]), float(naive["ci_high"][0])],
        "time_varying_hr": float(tv["hr"][0]),
        "time_varying_ci": [float(tv["ci_low"][0]), float(tv["ci_high"][0])],
        "truth": z["truth"]["hr_treatment"],
        "immortal_person_months": immortal_months,
    }

    # =====================================================================
    print("\n" + "=" * 76)
    print("PRE-SPECIFIED vs EXPLORATORY")
    print("=" * 76)
    print("  PRE-SPECIFIED (written before looking at outcomes):")
    print("    - primary: overall survival, treatment vs control, log-rank")
    print("    - adjusted: Cox with age and stage")
    print("    - PH assumption checked by Schoenfeld residuals")
    print("  EXPLORATORY (hypothesis-generating only, no inference claimed):")
    if violated:
        print("    - the stratified model, fitted BECAUSE the PH test failed")
        print("      (a model chosen in response to the data is exploratory,")
        print("      however well motivated the choice was)")
    else:
        print("    - none fitted in this run: the PH test did not fail, so no")
        print("      data-driven model change was made. Had it failed, the")
        print("      stratified model would appear here rather than above,")
        print("      because a model chosen in response to the data is")
        print("      exploratory however well motivated the choice was.")
    print("    - any subgroup pattern visible in the curves")
    print("\n  The line matters because a p-value computed after seeing the")
    print("  data does not mean what a p-value means. Everything below the")
    print("  line can motivate the next trial; none of it can support a claim")
    print("  in this one.")

    with open(f"{OUT}/results.json", "w") as fh:
        json.dump(payload, fh, indent=2, default=str)
    print(f"\nwrote {OUT}/results.json")
    return payload


if __name__ == "__main__":
    main()
