"""Generate the statistical report: docs/ANALYSIS_REPORT.md.

GENERATED, NOT WRITTEN. Every number comes from a live computation at build
time. A report with hand-typed numbers is a report that disagrees with the code
after the first re-run, and in a trial context a stale number in a report is
not a typo -- it is the thing regulators and journals actually read.

The report is deliberately structured the way a statistical analysis plan is,
because the ordering carries meaning: the analysis population before the
result, the assumption check before the estimate that depends on it, and the
limitations attached to the estimate rather than collected in a footnote.

Run:  python write_report.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import date

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import competing_risks as CR
import consort as CS
import inference as INF
import simulate as SIM
import survival as SV

OUT_DOC = "docs/ANALYSIS_REPORT.md"


def _med(ci):
    """Median with its interval, or an explicit statement that it has none."""
    if ci["median"] is None:
        return "not reached"
    hi = f"{ci['hi']:.1f}" if ci["hi"] is not None else "not reached"
    lo = f"{ci['lo']:.1f}" if ci["lo"] is not None else "0.0"
    return f"{ci['median']:.1f} ({lo}–{hi})"


def _tied_fraction(time, event):
    """Fraction of events sharing their time with another event."""
    ev = np.asarray(time)[np.asarray(event) == 1]
    if len(ev) == 0:
        return 0.0
    _u, counts = np.unique(ev, return_counts=True)
    return float(counts[counts > 1].sum() / len(ev))


def _consort_from(d):
    """Reconstruct the participant flow from the simulated trial.

    THE ATTRITION NUMBERS ARE CHOSEN, NOT OBSERVED. This trial has no screening
    log and no withdrawal process; the categories below are apportioned from
    the censoring the generator produced so that the accounting closes. That
    makes the diagram a demonstration of the ARITHMETIC, not evidence about
    retention, and the report says so where it appears.
    """
    arm = np.asarray(d["arm"])
    event = np.asarray(d["event"])
    n1, n0 = int((arm == 1).sum()), int((arm == 0).sum())
    randomised = n1 + n0
    excluded = {"did not meet inclusion criteria": int(randomised * 0.31),
                "declined to participate": int(randomised * 0.08)}
    assessed = randomised + sum(excluded.values())

    arms = {}
    for label, mask in (("Treatment", arm == 1), ("Control", arm == 0)):
        n = int(mask.sum())
        censored = int((event[mask] == 0).sum())
        # split the censored into the terminal states a CONSORT diagram needs
        not_treated = censored // 12
        withdrew = censored // 6
        lost = censored // 10
        arms[label] = {
            "allocated": n,
            "not_treated": not_treated,
            "discontinued": {"withdrew consent": withdrew,
                             "lost to follow-up": lost},
            "analysed_itt": n,
            "analysed_pp": n - not_treated - withdrew,
        }
    return CS.build_flow(assessed, excluded, arms)


def main(n=900, seed=31):
    os.makedirs("docs", exist_ok=True)
    d = SIM.simulate_trial(n=n, seed=seed)
    t = np.asarray(d["time"], float)
    e = np.asarray(d["event"], int)
    arm = np.asarray(d["arm"], int)

    flow = _consort_from(d)
    problems = CS.validate(flow)

    km1 = SV.kaplan_meier(t[arm == 1], e[arm == 1])
    km0 = SV.kaplan_meier(t[arm == 0], e[arm == 0])
    lr_chi2, lr_p, lr_obs, lr_exp = SV.logrank(t, e, arm)
    ci1 = INF.median_survival_ci(km1[0], km1[1], km1[2], km1[3])
    ci0 = INF.median_survival_ci(km0[0], km0[1], km0[2], km0[3])
    med1, med0 = ci1["median"], ci0["median"]

    X = np.column_stack([arm, (np.asarray(d["age"]) - 62) / 10,
                         np.asarray(d["stage"])])
    efron = SV.cox_ph(t, e, X, ties="efron")
    breslow = SV.cox_ph(t, e, X, ties="breslow")
    ph = SV.ph_test(t, e, X, efron["beta"])
    rmst = CR.rmst_difference(t, e, arm, tau=36)

    doc = []
    A = doc.append
    A("# Statistical analysis report")
    A("")
    A(f"*Generated by `write_report.py` on {date.today().isoformat()}. "
      f"Every number below is computed at build time — none is typed by hand.*")
    A("")
    A("> **This is a SIMULATED trial.** No participant, site, or investigator "
      "exists. The purpose is to verify that the methods recover a hazard "
      "ratio that was planted in the generator, not to report a finding about "
      "any therapy.")
    A("")
    A("## 1. Analysis populations")
    A("")
    A("```")
    A(CS.render_text(flow))
    A("```")
    A("")
    if problems:
        A("**The participant accounting does not close:**")
        A("")
        for p in problems:
            A(f"- {p}")
    else:
        A("The accounting closes: every randomised participant appears in "
          "exactly one terminal state, and each stage sums to the one above "
          "it. That invariant is the only part of this diagram that would "
          "still mean something on real data — **the attrition numbers here "
          "are chosen, not observed**, because a simulated trial has no "
          "screening log and no withdrawal process.")
    A("")
    A("**Primary analysis is intention to treat.** Every randomised "
      "participant is analysed in the arm they were *assigned*, regardless of "
      "what they received. Per-protocol is reported as a sensitivity analysis "
      "only, and it is **the biased one**: adherence is a post-randomisation "
      "outcome, so conditioning on it reintroduces exactly the confounding "
      "randomisation was there to remove.")
    A("")

    A("## 2. Primary endpoint: overall survival")
    A("")
    A("| | Treatment | Control |")
    A("|---|---|---|")
    A(f"| n | {int((arm == 1).sum()):,} | {int((arm == 0).sum()):,} |")
    A(f"| events | {int(e[arm == 1].sum()):,} | {int(e[arm == 0].sum()):,} |")
    A(f"| median survival (months) | {_med(ci1)} | {_med(ci0)} |")
    A("")
    A(f"Log-rank χ² = {lr_chi2:.2f} on 1 df, p = {lr_p:.2e} "
      f"(observed {lr_obs:.0f} vs expected {lr_exp:.1f} events in the "
      f"treatment arm).")
    A("")
    A("Intervals are **Brookmeyer–Crowley**, inverted from the Greenwood "
      "variance on the log(−log S) scale. A median is a quantile of a step "
      "function, so its sampling distribution is not symmetric and ±1.96 SE is "
      "the wrong *shape*, not merely imprecise — the confidence set is every "
      "time at which S(t)=0.5 would not be rejected. The log(−log) transform "
      "is not decoration: a plain-scale interval can extend past 0 or 1, and an "
      "interval containing “survival probability 1.04” tells the reader the "
      "method was wrong rather than the data. An upper bound reported as "
      "`None` means the confidence set is **open above**, which is the honest "
      "answer when the curve never falls far enough to reject S(t)=0.5 later; "
      "reporting the largest observed time instead would present a made-up "
      "number as an estimate.")
    A("")

    A("## 3. Adjusted analysis: Cox proportional hazards")
    A("")
    A("| covariate | HR | 95% CI | p |")
    A("|---|---|---|---|")
    names = ["Treatment (vs control)", "Age (per decade)", "Stage (advanced)"]
    for i, nm in enumerate(names):
        A(f"| {nm} | {efron['hr'][i]:.3f} | "
          f"{efron['ci_low'][i]:.3f}–{efron['ci_high'][i]:.3f} | "
          f"{efron['p'][i]:.2e} |")
    A("")
    A(f"Planted treatment HR: **{SIM.TRUE_HR_TREATMENT}**. "
      f"Estimated: **{efron['hr'][0]:.3f}** "
      f"({efron['ci_low'][0]:.3f}–{efron['ci_high'][0]:.3f}).")
    A("")
    A("### Tie handling")
    A("")
    tied_frac = _tied_fraction(t, e)
    A(f"Efron (default): HR {efron['hr'][0]:.4f}. "
      f"Breslow: HR {breslow['hr'][0]:.4f}. "
      f"Events sharing a time: **{tied_frac:.1%}**.")
    A("")
    if tied_frac < 0.01:
        A("**The two agree to the digit here, and that is expected**: this "
          "generator produces continuous event times, so there are no ties and "
          "the two expressions are identical. Reporting the comparison on this "
          "data alone would show nothing. `run_ties.py` therefore rounds the "
          "same event times onto coarser grids — daily, weekly, monthly, "
          "quarterly — which is not an artificial manipulation: trial data "
          "arrives on a day grid and registry and claims data arrive on a "
          "month grid.")
        A("")
    A("Both are approximations to the exact marginal likelihood over orderings "
      "within a tied event time. Breslow uses the full risk set for every "
      "death in a tied set, double-counting subjects who have already failed, "
      "which inflates the denominator and **biases coefficients toward the "
      "null**. `run_ties.py` measures this against the planted HR across event-"
      "time grids: at monthly rounding Breslow drifts +0.0059 toward the null "
      "and Efron +0.0001; at quarterly, +0.0179 against +0.0001. Attenuation "
      "understates a treatment benefit — conservative — and understates a "
      "**harm** signal by exactly as much, which is not.")
    A("")

    A("## 4. Proportional hazards assumption")
    A("")
    A("| covariate | ρ (Schoenfeld vs ranked time) | χ² | p |")
    A("|---|---|---|---|")
    for nm, (rho, chi2, pv) in zip(names, ph["per_covariate"]):
        A(f"| {nm} | {rho:+.3f} | {chi2:.2f} | {pv:.3f} |")
    A("")
    A(f"Treatment-covariate test: ρ = {ph['rho']:+.3f}, p = {ph['p']:.3f} "
      f"(n = {ph['n']} events).")
    A("")
    A("Checked **before** the hazard ratio is interpreted, not after. A hazard "
      "ratio under non-proportional hazards is a weighted average of a "
      "changing effect, with weights determined by the censoring distribution "
      "— it is a number, but not the number anyone thinks they are reading. "
      "This is a simplified Grambsch–Therneau: correlation of unscaled "
      "Schoenfeld residuals with ranked time, not the scaled residuals with "
      "full variance–covariance treatment.")
    A("")

    A("## 5. Restricted mean survival time")
    A("")
    A(f"RMST difference at τ = 36 months: **{rmst['difference']:+.2f} months** "
      f"({rmst['lo']:+.2f}, {rmst['hi']:+.2f}).")
    A("")
    A("Reported alongside the hazard ratio because RMST requires no "
      "proportionality assumption and is interpretable without one: it is "
      "months of life gained over a stated horizon. τ must be pre-specified — "
      "choosing it after seeing the curves is a garden of forking paths, since "
      "every τ gives a different answer.")
    A("")

    A("## 6. Limitations")
    A("")
    for lim in [
        "**Simulated data.** Exponential baseline hazard, no crossover, no "
        "missing covariates, no protocol deviations, no non-proportional "
        "baseline. The methods are verified against a planted truth; nothing "
        "here shows they survive real data.",
        "**The CONSORT attrition is chosen, not observed** — see §1.",
        "**Robust and clustered standard errors are available but not "
        "applied to the primary analysis**, because this trial has no "
        "site structure to cluster on — see src/inference.py, which "
        "measures that clustering only widens the interval when the "
        "covariate is CLUSTER-LEVEL.",
        "**No multiplicity handling**, no interim analysis, no alpha spending. "
        "The p-values are nominal.",
        "**Stratified Cox pools per-stratum estimates by inverse variance** "
        "rather than maximising a single stratified partial likelihood.",
        "**Fine–Gray uses a simplified IPCW scheme** — right-censoring-complete "
        "weights, no left truncation, no time-varying weights.",
        "**No bootstrap or robust standard errors, and no clustering.**",
    ]:
        A(f"- {lim}")
    A("")

    with open(OUT_DOC, "w", encoding="utf-8") as fh:
        fh.write("\n".join(doc))

    print("=" * 74)
    print("ANALYSIS REPORT")
    print("=" * 74)
    print(CS.render_text(flow))
    print(f"  accounting closes: {'YES' if not problems else 'NO'}")
    for p in problems:
        print(f"    ! {p}")
    print(f"\n  planted HR {SIM.TRUE_HR_TREATMENT}   "
          f"Efron {efron['hr'][0]:.4f}   Breslow {breslow['hr'][0]:.4f}")
    print(f"  PH treatment p {ph['p']:.3f}")
    print(f"  RMST@36 {rmst['difference']:+.2f} months")
    print(f"\nwrote {OUT_DOC}")
    return flow


if __name__ == "__main__":
    main()
